services:
  db:
    image: postgres:15
    container_name: meteo-db
    env_file:
      - .env
    ports:
      - 5436:5432
    restart: always
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 10s
      retries: 5

  migrations:
    build: .
    container_name: meteo-service-migrations-tool
    command: sh -c "alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  web:
    build: .
    container_name: meteo-service
    command: sh -c "uvicorn --factory src.main:create_app --host=0.0.0.0 --port=8080"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - 8003:8080
    restart: always

volumes:
  pgdbdata:

networks:
  default:
    name: agronetwork
    external: true